//"use client";
import 'bootstrap/dist/css/bootstrap.min.css';
import Styles from './globals.css';
import Link from 'next/link'
import { Controls } from './Controls';
//import { useState } from 'react';

export const metadata = {
  title: "Web Tutorials",
  description: "Generated by Green",
};

export default async function RootLayout({ children }) {
  console.log('공통 레이아웃 작동');
  /* 사용하면 metadata 사용 시, 오류가 발생한다. 그래서 fetch문법으로 변경!!! 🔔
  const [topics, setTopics] = useState([]);
  
  useEffect(()=>{
    fetch('http://localhost:9999/topics/')
    .then(r=>r.json())
    .then(result=>{
      setTopics(result)
    });
  },[]);
  */
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}topics`,{ cache: 'no-store' }); //조회
  const topics = await res.json(); // json->object에 담기면 topic에 담는다
  
  return (
    <html lang="en">
      <body>
        <nav className="navbar bg-light">
          <div className="container">
            <Link href="/" className="navbar-brand">WEB</Link>
            <ul className="nav">
              {
              topics.map(item =>
                  <li key={item.id} className="nav-item">
                    <Link href={`/read/${item.id}`} className="nav-link">{item.title}</Link>
                  </li>
                )
              }
            </ul>
          </div>
        </nav>
        <main className="container my-3">
          {children}
          <hr/>
          <Controls/>
        </main>
      </body>
    </html>
  );
}
